import 'package:test/test.dart';
import 'package:piped_api/piped_api.dart';

// tests for Subtitle
void main() {
  final instance = SubtitleBuilder();
  // TODO add properties to the builder and call build()

  group(Subtitle, () {
    // Whether the subtitle is auto generated.
    // bool autoGenerated
    test('to test the property `autoGenerated`', () async {
      // TODO
    });

    // The language code of the subtitle.
    // String code
    test('to test the property `code`', () async {
      // TODO
    });

    // The mime type of the subtitle.
    // String mimeType
    test('to test the property `mimeType`', () async {
      // TODO
    });

    // The URL of the subtitle.
    // String url
    test('to test the property `url`', () async {
      // TODO
    });

  });
}
